apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: resource-portal-ci-run-
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push, pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "main"
    pipelinesascode.tekton.dev/max-keep-runs: "5"
  labels:
    pipelinesascode.tekton.dev/repository: git-resource-allocation-portal-on-open-shift-git
spec:
  pipelineRef:
    name: resource-portal-pipeline
  params:
    - name: CLIENT_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/poc-cs-resource-utilization-portal/client-app
    - name: SERVER_IMAGE
      value: image-registry.openshift-image-registry.svc:5000/poc-cs-resource-utilization-portal/server-app
    - name: repo_url
      value: '{{ repo_url }}'
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        metadata:
          name: shared-pvc
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
